import { AppData } from './types'

export const seedData: AppData = {
  usuarios: [
    { id: 'u1', nombre: 'Administrador', email: 'admin@kimar.com', rol: 'admin', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'u2', nombre: 'Gestor', email: 'gestor@kimar.com', rol: 'gestor', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'u3', nombre: 'Marcos', email: 'marcos@kimar.com', rol: 'vendedor', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'u4', nombre: 'Lucho', email: 'lucho@kimar.com', rol: 'vendedor', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'u5', nombre: 'Lucas', email: 'lucas@kimar.com', rol: 'vendedor', activo: true, fechaCreacion: '2025-01-01' },
  ],
  vendedores: [
    { id: 'v1', nombre: 'Marcos', usuarioId: 'u3', activo: true },
    { id: 'v2', nombre: 'Lucho', usuarioId: 'u4', activo: true },
    { id: 'v3', nombre: 'Lucas', usuarioId: 'u5', activo: true },
  ],
  clientes: [
    // Cartera Marcos
    { id: 'c1', nombre: 'Augusta', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c2', nombre: 'Daimus', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c3', nombre: 'La Segunda', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c4', nombre: 'Haro Sushi', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c5', nombre: 'El Viejo Cañón', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c6', nombre: 'Longobucco', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c7', nombre: 'Hormiga Negra - Urquiza', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c8', nombre: 'Hormiga Negra - Olivos', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c9', nombre: 'Hormiga Negra - San Fernando', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c10', nombre: 'Sushi Kyu', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c11', nombre: 'Lili Resto', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c12', nombre: 'Pescería', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c13', nombre: 'Ercopez', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c14', nombre: 'Chirola Teresa', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c15', nombre: 'Gabriel Teresa', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c16', nombre: 'Kity', vendedorId: 'v1', activo: true, fechaCreacion: '2025-01-01' },
    // Cartera Lucho
    { id: 'c17', nombre: 'Sushi Club - Delta', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c18', nombre: 'Sushi Club - Mastwichtz', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c19', nombre: 'Sushi Club - Lomas', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c20', nombre: 'Satoshi 1', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c21', nombre: 'Satoshi 2', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c22', nombre: 'Fabirc Castelar', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c23', nombre: 'Fabirc Leloir', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c24', nombre: 'Fabric Federico X9', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c25', nombre: 'Fabric Peñaloza', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c26', nombre: 'El Pibe Dorrego', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c27', nombre: 'Polo House - Salón Recova', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c28', nombre: 'Cochinchina', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c29', nombre: 'Polo Catering / Solpen', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c30', nombre: 'Fabric Polo', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c31', nombre: 'Olivos Gourmet', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c32', nombre: 'Cachito de Mar', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c33', nombre: 'The Fish Company', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c34', nombre: 'Alvasan', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c35', nombre: 'Eduardo Gazzo', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c36', nombre: 'Pescadería: El Tiburón de Flo', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c37', nombre: 'Pescadería: La Esperanza', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c38', nombre: 'Pescadería: Biancomar', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c39', nombre: 'Pescadería: Luigi', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c40', nombre: 'Pescadería: Sorrento', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c41', nombre: 'Pescadería: Il Pesce', vendedorId: 'v2', activo: true, fechaCreacion: '2025-01-01' },
    // Cartera Lucas
    { id: 'c42', nombre: 'Toscana', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c43', nombre: 'Moby Dick', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c44', nombre: 'Yunta', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c45', nombre: 'Sta. Barbara - Olivos - Ugarte', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c46', nombre: 'Sta. Barbara - Devoto - Natalia', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c47', nombre: 'Barbacoa', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c48', nombre: 'Moncada', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c49', nombre: 'El Imparcial', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c50', nombre: 'El Globo', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c51', nombre: 'Claudio Ramos Mejía', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c52', nombre: 'Florencia China', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c53', nombre: 'Jacinto', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c54', nombre: 'Aurelia Río', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c55', nombre: 'Super Chino Wu', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c56', nombre: 'Distribuidora: Ostra Azul', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c57', nombre: 'Distribuidora: Islamar - Ismael', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c58', nombre: 'Bajos del Paraná: Claudio Achaval', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c59', nombre: 'Pescadería: Tornadore', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c60', nombre: 'Pescadería: Modelo', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c61', nombre: 'Pescadería: Tito', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c62', nombre: 'Pescadería: Cayetano', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c63', nombre: 'Pescadería: Golfo', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c64', nombre: 'Pescadería: Carbone', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c65', nombre: 'Pescadería: Mi Puerto', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c66', nombre: 'Pescadería: Liniers', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
    { id: 'c67', nombre: 'Pescadería Chuchu', vendedorId: 'v3', activo: true, fechaCreacion: '2025-01-01' },
  ],
  productos: [
    { id: 'p1', nombre: 'Tubo de Calamar IQF', categoria: 'calamares', precioKg: 12500, unidad: 'kg', activo: true },
    { id: 'p2', nombre: 'Tubo de Calamar - Iberconsa M', categoria: 'calamares', precioKg: 15900, unidad: 'kg', activo: true },
    { id: 'p3', nombre: 'Anillas de Calamar - Iberconsa', categoria: 'calamares', precioKg: 13500, unidad: 'kg', activo: true },
    { id: 'p4', nombre: 'Tentáculo de Calamar', categoria: 'calamares', precioKg: 8500, unidad: 'kg', activo: true },
    { id: 'p5', nombre: 'Aleta de Calamar', categoria: 'calamares', precioKg: 6500, unidad: 'kg', activo: true },
    { id: 'p6', nombre: 'Langostino Entero N°1 - Lanzal', categoria: 'langostinos', precioKg: 11500, unidad: 'kg', activo: true },
    { id: 'p7', nombre: 'Langostino Entero N°2 - Lanzal', categoria: 'langostinos', precioKg: 10500, unidad: 'kg', activo: true },
    { id: 'p8', nombre: 'Cola de Langostino N°0 - Lanzal', categoria: 'langostinos', precioKg: 12500, unidad: 'kg', activo: true },
    { id: 'p9', nombre: 'Cola de Langostino N°1 - Lanzal', categoria: 'langostinos', precioKg: 11500, unidad: 'kg', activo: true },
    { id: 'p10', nombre: 'Cola de Langostino N°2 - Lanzal', categoria: 'langostinos', precioKg: 10500, unidad: 'kg', activo: true },
    { id: 'p11', nombre: 'Cola de Langostino IQF - Lanzal', categoria: 'langostinos', precioKg: 9900, unidad: 'kg', activo: true },
    { id: 'p12', nombre: 'Langostino Pelado sin vena - Lanzal', categoria: 'langostinos', precioKg: 14900, unidad: 'kg', activo: true },
    { id: 'p13', nombre: 'Langostino Pelado roto - Lanzal', categoria: 'langostinos', precioKg: 10900, unidad: 'kg', activo: true },
    { id: 'p14', nombre: 'Kanikama - Sta. Helena industrial', categoria: 'langostinos', precioKg: 13900, unidad: 'kg', activo: true },
    { id: 'p15', nombre: 'Ostiones ½ valva', categoria: 'bivalvos', precioKg: 32000, unidad: 'kg', activo: true },
    { id: 'p16', nombre: 'Callos de Vieiras', categoria: 'bivalvos', precioKg: 38000, unidad: 'kg', activo: true },
    { id: 'p17', nombre: 'Mejillón ½ valva', categoria: 'bivalvos', precioKg: 10900, unidad: 'kg', activo: true },
    { id: 'p18', nombre: 'Mejillón Pelado', categoria: 'bivalvos', precioKg: 7900, unidad: 'kg', activo: true },
    { id: 'p19', nombre: 'Cornalitos', categoria: 'bivalvos', precioKg: 10500, unidad: 'kg', activo: true },
    { id: 'p20', nombre: 'Atún Rojo', categoria: 'pescados', precioKg: 33500, unidad: 'kg', activo: true },
    { id: 'p21', nombre: 'Salmón Ahumado', categoria: 'pescados', precioKg: 35000, unidad: 'kg', activo: true },
    { id: 'p22', nombre: 'Filet de Salmón', categoria: 'pescados', precioKg: 25900, unidad: 'kg', activo: true },
    { id: 'p23', nombre: 'Filet de Trucha', categoria: 'pescados', precioKg: 20900, unidad: 'kg', activo: true },
    { id: 'p24', nombre: 'Filet Pesca Blanca del día', categoria: 'pescados', precioKg: 10500, unidad: 'kg', activo: true },
    { id: 'p25', nombre: 'Filet de Abadejo', categoria: 'pescados', precioKg: 13500, unidad: 'kg', activo: true },
    { id: 'p26', nombre: 'Filet de Merluza', categoria: 'pescados', precioKg: 7000, unidad: 'kg', activo: true },
    { id: 'p27', nombre: 'Merluza Negra troncos 6-10 kg', categoria: 'pescados', precioKg: 39500, unidad: 'kg', activo: true },
    { id: 'p28', nombre: 'Pulpo Español T1', categoria: 'pulpos', precioKg: 34000, unidad: 'kg', activo: true },
    { id: 'p29', nombre: 'Pulpo Español T2', categoria: 'pulpos', precioKg: 36000, unidad: 'kg', activo: true },
    { id: 'p30', nombre: 'Centolla Mix', categoria: 'otros', precioKg: 95000, unidad: 'kg', activo: true },
  ],
  pedidos: [],
  ventas: [],
  cobranzas: [],
  proveedores: [],
  compromisosProveedor: [],
  movimientosStock: [],
  gastosFijos: [],
  instanciasGasto: [],
}
